---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wedding-hall-secrets
  namespace: wedding-hall
spec:
  encryptedData:
    WHATSAPP_NUMBER: AgCBUj//w/0wOf6bSdOtYc1Wp6EZ/545Vp9VQRjXkUC1dfB37jfLMafWMWTyBvBTwAKPZcOswVNWYN7gtWPB8R2S7SBgpPjXslA7g0NhRhXTrySvQI9JBrMGzCBro7Wylc1s3gHvn9mcTm4cccLZSE+PPH212Y8fuzDL88/5zSY4tEDhfO/OmOnhAGLubtb6sVyVsDoZE+wfRBjz0wpOHR5WBwVzj3QwVPpFeuuCaiwyK5neMuF5F5JNDSqoZlUiFpi2PZKB6od95PES3IFdPHoLSut5oonN2NUuKgsoHB8pht/WKpnwt3kpIbaYL9CdbASv1tdolY6ELZoVTL/PhiwICGXb/FcuIq/mIUR1QM27hEInIeVEf7HQJ/Mj1G3dR1ZcdP4IEa8hJZ/gZTlbwUJKpsJneyCekvsPK3v+FwWBzSLOuRfAbAOFXRuJRy00B1tl31xEz+E3DXbmBdy6OjkHovx1YfPGitVdyxJ/4d6xS7nNnl3HW2WsbsB60dv1798siTVPRR01IqGZg2ZSd12Qicsray+PkmwNuS45jAMUyNCSLcNv0DfncJcSWrVZhwLSGOSDEjTTF7o9Tzb6eHhpK9t/DWTWswLIZ4bbPsLGusJTDtLcjF0CJxM8O5hbNxDLBkQ1QCgD43R6m5Wtk48cYeeYxGyIymdSjhrYVOJuDS1cRHiaJH+fR/djDAxojUzkYQykmsN0NblllKE=
  template:
    metadata:
      creationTimestamp: null
      name: wedding-hall-secrets
      namespace: wedding-hall
