replicaCount: 1

image:
  repository: jamalafridi99/wedding-hall
  tag: "89ad00fcbc11568868adc23d83aec288fc667241"
  pullPolicy: Always

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  hosts:
    - host: grandeurlounge.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wedding-hall-tls
      hosts:
        - grandeurlounge.site

autoscaling:
  enabled: false
