replicaCount: 1

image:
  repository: jamalafridi99/wedding-hall
  tag: "c030a8495c5ea4664f374f2b92705bb7c92c1a35"
  pullPolicy: Always

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  hosts:
    - host: wedding-hall.dev.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wedding-hall-tls
      hosts:
        - wedding-hall.dev.local

autoscaling:
  enabled: false
