replicaCount: 1

image:
  repository: jamalafridi99/wedding-hall
  tag: "c93e76d4e5333af70eba4bc6d34103ac44fd5a6e"
  pullPolicy: Always

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: wedding-hall.dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
